### ISSUE TITLE
myproject_db failing to connect on ubuntu terminal

### ISSUE THREAD

**Issue by Surya9339** [philgyford/django-docker-example#5]
Hi Team,

I followed the README.md instructions. They are working good in my Mac[personal workstation] but they are giving following  in ubuntu[WindowsSubLinux].
```
myproject_web  | Loading .env environment variables...
myproject_db   | 2022-05-30 02:59:49.861 UTC [69] FATAL:  password authentication failed for user "admin"
myproject_db   | 2022-05-30 02:59:49.861 UTC [69] DETAIL:  Role "admin" does not exist.
myproject_db   |        Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
myproject_web  | Traceback (most recent call last):
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
myproject_web  |     self.connect()
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
myproject_web  |     return func(*args, **kwargs)
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
myproject_web  |     self.connection = self.get_new_connection(conn_params)
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
myproject_web  |     return func(*args, **kwargs)
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
myproject_web  |     connection = Database.connect(**conn_params)
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
myproject_web  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
myproject_web  | psycopg2.OperationalError: connection to server at "myproject_db" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "admin"
myproject_web  |
myproject_web  |
myproject_web  | The above exception was the direct cause of the following exception:
myproject_web  |
myproject_web  | Traceback (most recent call last):
myproject_web  |   File "manage.py", line 22, in <module>
myproject_web  |     main()
myproject_web  |   File "manage.py", line 18, in main
myproject_web  |     execute_from_command_line(sys.argv)
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
myproject_web  |     utility.execute()
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
myproject_web  |     self.fetch_command(subcommand).run_from_argv(self.argv)
myproject_web  |   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
myproject_web  |     self.execute(*args, **cmd_options)
```

Can someone take a look and advise.

**Comment by philgyford** [comment]
My guess would be that you don't have the correct username and/or password for the database:

    myproject_web  | psycopg2.OperationalError: connection to server at "myproject_db" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "admin"

Double-check your `.env` file and what the database is expecting.

**Comment by Surya9339** [comment]
> My guess would be that you don't have the correct username and/or password for the database:
> 
> ```
> myproject_web  | psycopg2.OperationalError: connection to server at "myproject_db" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "admin"
> ```
> 
> Double-check your `.env` file and what the database is expecting.

This is data given in .env file , the same data worked good on mac but throwing error in windows


# Environment settings for local development.

POSTGRES_USER=admin
POSTGRES_PASSWORD=PassW0rD@123
POSTGRES_DB=mydatabase
POSTGRES_HOST=myproject_db

DJANGO_SETTINGS_MODULE=myproject.myproject.settings.development

**Comment by philgyford** [comment]
Are you connecting to the same database? Can you manually connect to the database using the same credentials?

    docker exec -it myproject_db psql -U admin -d mydatabase
